### ISSUE TITLE
Can't serve static files and use template at the same time.

### ISSUE THREAD

**Issue by charmstead** [aeberdinelli/express-php#5]
Why can't i set the directory for my static files and still use template at the same time?
each time i call  //
`$router->use('', $express->static('public'));` 
i get the error.
`Fatal error: Uncaught Exception: Could not handle /. File public/index.html not found in /app/src/Express/ExpressStatic.php:799 Stack trace: #0 /app/src/Express/Router.php(74): Express\ExpressStatic->init('') #1 /app/index.php(16): Express\Router->use('', Object(Express\ExpressStatic)) #2 {main} thrown in /app/src/Express/ExpressStatic.php on line 799`

if i can't do this then it means i won't be able to reference my static assets from my template files.

Node Express lets me do this.

I will also love to see a version where express let's me specify directory for partials.
or better still support handlebars template engine.

**Comment by aeberdinelli** [comment]
hello @charmstead , you should be able to use both a static directory and template, the problem is that since you're not directly handling the request to `/` it will try to fetch the `index.html` in your static folder. You can try this:

```
<?php
$router->use('', $express->static('public'));

$router->get('/', function($req, $res) {
    $res->render('index.pug');
});
?>

That should work! I will try to add some logic to handle cases like this automatically, thank you for reporting this 🙂
