### ISSUE TITLE
The event loop is missing.

### ISSUE THREAD

**Issue by viper-hq** [aeberdinelli/express-php#7]

**Comment by aeberdinelli** [comment]
What do you mean? The framework's architecture is not like the one in nodejs, this one is not based on events, it just mimics how you'd write the controllers for each endpoints but they work completely different. In Express you would write event handlers while here you would create an array for each route and method mapped to a function, then when it receives a request it checks which function it should call. 

Please keep in mind this was written just for learning purposes, not to be a Express JS clone. I hope I solved your doubts 😄

**Comment by viper-hq** [comment]
It could use react php. I'm a NodeJS guy but me and others would definitely try something like that.

https://reactphp.org/
