### ISSUE TITLE
PHP Notice:  Undefined index: QUERY_STRING

### ISSUE THREAD

**Issue by almadrasa** [aeberdinelli/express-php#8]

**Comment by almadrasa** [comment]
how to delete this, i was wrong , in the url i forget to use "?" tha'ts why i didn't get the query

**Comment by aeberdinelli** [comment]
@almadrasa sorry I didn't reply earlier, don't worry you already closed it! Thank you. Keep in mind that is just a notice, you can change your error logs to ignore that log level since they aren't usually critical stuff.
